version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: energy_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/energy_db
    command: tail -f /dev/null  # Para mantener el contenedor activo y poder entrar con bash

volumes:
  postgres_data:
