FROM python:3.11-slim

# Evitar problemas de buffering y establecer el PYTHONPATH a la raíz del proyecto
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

# Directorio de trabajo (la raíz del proyecto se copiará en /app)
WORKDIR /app

# Copiar e instalar dependencias
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copiar el resto del proyecto
COPY . .

# Comando por defecto: ejecuta el punto de entrada
CMD ["python", "main.py"]
